import Config

# Load environment variables from .env file
env_path = Path.join(__DIR__, "../.env")
if File.exists?(env_path) do
  for line <- File.stream!(env_path) do
    line = String.trim(line)
    if line != "" && !String.starts_with?(line, "#") do
      [key, value] = String.split(line, "=", parts: 2)
      System.put_env(String.trim(key), String.trim(value))
    end
  end
end

# Configure your database
config :streamystat_server, StreamystatServer.Repo,
  username: System.get_env("DATABASE_USERNAME", "postgres"),
  password: System.get_env("DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DATABASE_HOSTNAME", "localhost"),
  database: System.get_env("DATABASE_NAME", "streamystat_server_dev"),
  port: String.to_integer(System.get_env("DATABASE_PORT", "5432")),
  pool_size: String.to_integer(System.get_env("DATABASE_POOL_SIZE", "10")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false,
  adapter: Postgrex,
  types: StreamystatServer.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :streamystat_server, StreamystatServerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "XEUqo2CvNzoDqPMea93ijjna7btWWMpRiOlAiuqEOzYWwBq10mhJ4E6J4i7LzDUb",
  watchers: [],
  # Set Phoenix request logging to debug level instead of info
  log: :debug

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :streamystat_server, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  format: "$time [$level] $message\n",
  level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
